# Generated by Django 3.1.1 on 2023-08-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('MOVIE', 'Película'), ('SERIE', 'Serie')], max_length=50, verbose_name='Tipo')),
                ('categories', models.ManyToManyField(related_name='medias', to='medias.Category', verbose_name='Genero')),
            ],
        ),
    ]
