# Generated by Django 3.1.1 on 2023-08-26 16:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to=settings.AUTH_USER_MODEL, verbose_name='Espectador')),
            ],
        ),
        migrations.CreateModel(
            name='ViewerMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('has_watched', models.BooleanField(default=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_media', to='medias.media')),
                ('viewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social.viewer')),
            ],
        ),
        migrations.AddField(
            model_name='viewer',
            name='watched_medias',
            field=models.ManyToManyField(through='social.ViewerMedia', to='medias.Media'),
        ),
    ]
