# Generated by Django 3.1.1 on 2023-08-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewermedia',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.viewer'),
        ),
        migrations.AlterUniqueTogether(
            name='viewermedia',
            unique_together={('viewer', 'media')},
        ),
    ]
